func TestExpandIPPerms(t *testing.T) {
func TestExpandIPPerms_NegOneProtocol(t *testing.T) {
func TestExpandIPPerms_nonVPC(t *testing.T) {
func TestExpandListeners(t *testing.T) {
func TestExpandListeners_invalid(t *testing.T) {
func TestFlattenHealthCheck(t *testing.T) {
func TestExpandStringList(t *testing.T) {
func TestExpandStringListEmptyItems(t *testing.T) {
func TestExpandParameters(t *testing.T) {
func TestExpandRedshiftParameters(t *testing.T) {
func TestExpandElasticacheParameters(t *testing.T) {
func TestExpandStepAdjustments(t *testing.T) {
func TestFlattenParameters(t *testing.T) {
func TestFlattenRedshiftParameters(t *testing.T) {
func TestFlattenElasticacheParameters(t *testing.T) {
func TestExpandInstanceString(t *testing.T) {
func TestFlattenNetworkInterfacesPrivateIPAddresses(t *testing.T) {
func TestFlattenGroupIdentifiers(t *testing.T) {
func TestExpandPrivateIPAddresses(t *testing.T) {
func TestFlattenAttachment(t *testing.T) {
func TestFlattenAttachmentWhenNoInstanceId(t *testing.T) {
func TestFlattenStepAdjustments(t *testing.T) {
func TestFlattenResourceRecords(t *testing.T) {
func TestFlattenAsgEnabledMetrics(t *testing.T) {
func TestFlattenKinesisShardLevelMetrics(t *testing.T) {
func TestFlattenSecurityGroups(t *testing.T) {
func TestFlattenApiGatewayThrottleSettings(t *testing.T) {
func TestFlattenApiGatewayStageKeys(t *testing.T) {
func TestExpandPolicyAttributes(t *testing.T) {
func TestExpandPolicyAttributes_invalid(t *testing.T) {
func TestExpandPolicyAttributes_empty(t *testing.T) {
func TestFlattenPolicyAttributes(t *testing.T) {
func TestCheckYamlString(t *testing.T) {
func TestNormalizeCloudFormationTemplate(t *testing.T) {
func TestCognitoUserPoolSchemaAttributeMatchesStandardAttribute(t *testing.T) {
func TestCanonicalXML(t *testing.T) {
